-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 16:14:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_denuncias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_denuncias` ;

-- -----------------------------------------------------
-- Schema db_denuncias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_denuncias` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `db_denuncias` ;

-- -----------------------------------------------------
-- Table `db_denuncias`.`cuentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_denuncias`.`cuentas` ;

CREATE TABLE IF NOT EXISTS `db_denuncias`.`cuentas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` INT(11) NOT NULL,
  `banco` VARCHAR(25) NOT NULL,
  `locacion` VARCHAR(25) NOT NULL,
  `estafador` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_denuncias`.`locacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_denuncias`.`locacion` ;

CREATE TABLE IF NOT EXISTS `db_denuncias`.`locacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(25) NOT NULL,
  `ciudad` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_denuncias`.`victima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_denuncias`.`victima` ;

CREATE TABLE IF NOT EXISTS `db_denuncias`.`victima` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cedula` INT(8) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `locacion` VARCHAR(50) NOT NULL,
  `locacion_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `locacion_id`),
  UNIQUE INDEX `ced_victima` (`cedula` ASC) VISIBLE,
  INDEX `fk_victima_locacion1_idx` (`locacion_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_denuncias`.`estafador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_denuncias`.`estafador` ;

CREATE TABLE IF NOT EXISTS `db_denuncias`.`estafador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cedula` INT(8) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `locacion` VARCHAR(25) NOT NULL,
  `cuenta` INT NOT NULL,
  `cuentas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cuentas_id`),
  INDEX `fk_estafador_cuentas1_idx` (`cuentas_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_denuncias`.`denuncias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_denuncias`.`denuncias` ;

CREATE TABLE IF NOT EXISTS `db_denuncias`.`denuncias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `expediente` VARCHAR(20) NOT NULL,
  `victima` VARCHAR(50) NOT NULL,
  `fecha` DATE NOT NULL,
  `estafador` VARCHAR(50) NOT NULL,
  `localidad` VARCHAR(25) NOT NULL,
  `cuenta` INT(11) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `victima_id` INT(11) NOT NULL,
  `locacion_id` INT(11) NOT NULL,
  `estafador_id` INT(11) NOT NULL,
  `cuentas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `victima_id`, `locacion_id`, `estafador_id`, `cuentas_id`),
  UNIQUE INDEX `expediente` (`expediente` ASC) VISIBLE,
  INDEX `fk_denuncias_victima_idx` (`victima_id` ASC) VISIBLE,
  INDEX `fk_denuncias_locacion1_idx` (`locacion_id` ASC) VISIBLE,
  INDEX `fk_denuncias_estafador1_idx` (`estafador_id` ASC) VISIBLE,
  INDEX `fk_denuncias_cuentas1_idx` (`cuentas_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
